services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: nodejs
    ports:
      - "8080:80"
    restart: unless-stopped
    networks:
      - app-network

  webserver:
    container_name: webserver
    restart: unless-stopped
    depends_on:
      - nodejs
    build:
      context: ./nginx-conf
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
    networks:
      - app-network
  db:
    image: mysql:5.7.22
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: voentorg_db
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
  phpmyadmin:
    image: phpmyadmin
    restart: always
    container_name: phpmyadmin
    links:
      - db
#Docker Networks
networks:
  app-network:
    driver: bridge

#Volumes
volumes:
  dbdata:
    driver: local
